apiVersion: v1
name: zookeeper
home: https://thebluespire.com/kafka-distribution
version: 0.1.0
appVersion: "1.0"
description: A Helm chart for Enterprise Messaging Hub - Zookeeper
keywords:
- Apache Zookeeper
sources:
- https://github.com/bluespireinc/charts/tree/master/bluehub/v0.1.0
maintainers:
- name: bluespireinc
  email: SB@thebluespire.com
