apiVersion: v1
appVersion: "1.5.1"
description: Cloud Native storage for containers
name: storageos-operator
version: 0.2.16
tillerVersion: ">=2.10.0"
keywords:
- storage
- block-storage
- volume
- operator
home: https://storageos.com
icon: https://storageos.com/wp-content/themes/storageOS/images/logo.svg
sources:
- https://github.com/storageos
maintainers:
- name: croomes
  email: simon.croome@storageos.com
- name: darkowlzz
  email: sunny.gogoi@storageos.com
