# This configmap stores the sidecar proxy info and arguments needed
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpx-istio-sidecar-injector
  namespace: {{.Release.Namespace}}
  labels:
    app: cpx-sidecar-injector
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    istio: sidecar-injector
data:
  config: |-
    policy: enabled
    # If user does *NOT* want to inject sidecar on some pods based on label,
    # then mention such labels in 'neverInjectSelector' entry.
    # Note: This is valid only when istio's sidecar-injector image is running.
    # neverInjectSelector:
    #   - matchExpressions:
    #     - {key: citrix.com/no.sidecar, operator: Exists}
    # Here, if pod has a label citrix.com/no.sidecar, then sidecar won't be injected for that pod.
    template: |-
      containers:
      - name: istio-adaptor
        image: {{ .Values.istioAdaptor.image }}:{{ .Values.istioAdaptor.tag }}
        imagePullPolicy: {{ .Values.istioAdaptor.imagePullPolicy }} 
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: APPLICATION_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: NS_USER
          value: nsroot
        - name: NS_PASSWORD
          value: nsroot
        args:
        - -pilot-location
{{- if eq .Values.istioAdaptor.secureConnect true }}
        - {{ .Values.istioPilot.name}}.{{.Values.istioPilot.namespace }}:{{ .Values.istioPilot.secureGrpcPort }} # istio-pilot.istio-system:15011
{{- else }}
        - {{ .Values.istioPilot.name}}.{{.Values.istioPilot.namespace }}:{{ .Values.istioPilot.insecureGrpcPort }} # istio-pilot.istio-system:15010
{{- end }}
        - -proxy-type
        - {{ .Values.istioAdaptor.proxyType | default "sidecar" | quote }}
        - -pilot-SAN
        - {{ .Values.istioPilot.SAN }}
        - -netscaler-url
        - {{ .Values.istioAdaptor.netscalerUrl | default "http://127.0.0.1" | quote }}
        - -secure-connect={{ .Values.istioAdaptor.secureConnect}}
        - -adm-ip
{{- if .Values.istioAdaptor.ADMIP }}
        - {{ .Values.istioAdaptor.ADMIP }}
{{- else }}
        - ""
{{- end }}
{{- if .Values.istioAdaptor.coeURL }}
        - -coe-url
        - {{ .Values.istioAdaptor.coeURL }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
        - mountPath: /etc/nslogin 
          name: nslogin
          readOnly: true
      - name: cpx-proxy
        image: {{ .Values.cpxProxy.image }}:{{ .Values.cpxProxy.tag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: "EULA"
          value: "{{ .Values.cpxProxy.EULA }}"
        - name: "CPX_SIDECAR_MODE"
          value: {{ .Values.cpxProxy.cpxSidecarMode | quote }}
        - name: "MGMT_HTTP_PORT"
          value: {{ .Values.cpxProxy.mgmtHttpPort | quote }}
        - name: "MGMT_HTTPS_PORT"
          value: {{ .Values.cpxProxy.mgmtHttpsPort | quote }}
        - name: "KUBERNETES_TASK_ID"
          value: ""
        - name: "NS_CPX_LITE"
          value: 1
{{- if .Values.istioAdaptor.coeURL }}
        - name: "NS_ENABLE_NEWNSLOG"
          value: 1
{{- end }}
        - name: "LS_IP"
          value: {{ .Values.istioAdaptor.ADMIP | default "" }}
        - name: "LS_PORT"
          value: {{ .Values.cpxProxy.licenseServerPort}}
{{- if .Values.istioAdaptor.ADMFingerPrint }}
        - name: "NS_MGMT_SERVER"
          value: {{ .Values.istioAdaptor.ADMIP }}
        - name: "NS_MGMT_FINGER_PRINT"
          value: {{ .Values.istioAdaptor.ADMFingerPrint | quote }}
        - name: "NS_HTTP_PORT"
          value: {{ .Values.cpxProxy.mgmtHttpPort | quote }}
        - name: "NS_HTTPS_PORT"
          value: {{ .Values.cpxProxy.mgmtHttpsPort | quote }}
{{- end }}
        - name: "LOGSTREAM_COLLECTOR_IP"
          value: {{ .Values.istioAdaptor.ADMIP | default "" }}
      volumes:
      - name: nslogin
        secret:
          optional: true
          secretName: nslogin
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
---
