apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  name: {{ template "bluehub.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
