apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  name: {{ template "bluehub.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.port | default "9141" | int }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port | default "9141" | int }}
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
