{{ if .Values.defaultSecret }}
apiVersion: v1
data:
  zk_jaas.conf: Q2xpZW50IHsKICAgIG9yZy5hcGFjaGUuem9va2VlcGVyLnNlcnZlci5hdXRoLkRpZ2VzdExvZ2luTW9kdWxlIHJlcXVpcmVkCiAgICB1c2VybmFtZT0iem9va2VlcGVyIgogICAgcGFzc3dvcmQ9ImFkbWluc2VjcmV0IjsKfTsKClNlcnZlciB7CiAgICBvcmcuYXBhY2hlLnpvb2tlZXBlci5zZXJ2ZXIuYXV0aC5EaWdlc3RMb2dpbk1vZHVsZSByZXF1aXJlZAogICAgdXNlcl96b29rZWVwZXI9ImFkbWluc2VjcmV0IjsKfTsK
kind: Secret
metadata:
  name: {{ template "bluehub.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
