apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  name: {{ template "bluehub.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: client
    port: {{ .Values.service.port | default "2181" | int }}
    protocol: TCP
    targetPort: {{ .Values.service.port | default "2181" | int }}
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
