name: neuvector
apiVersion: v1
version: 1.2.3
appVersion: 2.4.2
description: NeuVector Container Security Platform includes layer 7 container firewall, end-to-end vulnerability scanning, and container process/file monitoring.
home: https://neuvector.com
icon: file://../NeuVector-Logo.png
maintainers:
  - name: Sun
    email: xfsun@neuvector.com
engine: gotpl
