apiVersion: v1
appVersion: "1.6.1"
description: A Helm chart for Citrix Ingress Controller configuring MPX/VPX
name: citrix-k8s-ingress-controller
version: 1.6.1
icon: file://../citrix_icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
- name: subashd
  email: subash.dangol@citrix.com
