dependencies:
- name: zookeeper
  version: 0.1.0
  repository: file://./charts/zookeeper
  condition: zookeeper.enabled
- name: kafka
  version: 0.1.0
  repository: file://./charts/kafka
  condition: kafka.enabled
- name: schemareg
  version: 0.1.0
  repository: file://./charts/schemareg
  condition: schemareg.enabled
- name: clustermgr
  version: 0.1.0
  repository: file://./charts/clustermgr
  condition: clustermgr.enabled
- name: securitymgr
  version: 0.1.0
  repository: file://./charts/securitymgr
  condition: securitymgr.enabled
- name: kproducer
  version: 0.1.0
  repository: file://./charts/kproducer
  condition: kproducer.enabled
