apiVersion: v1
name: harness-delegate
version: 1.0.0
appVersion: 1.0.0
description: Deploys harness delegate
home: https://harness.io/
icon: https://harness.io/wp-content/uploads/2019/07/logo-black.png
keywords:
- harness.io
- harness delegate
maintainers:
- email: anshul@harness.io
  name: anshul-harness
- email: puneet.saraswat@harness.io
  name: puneetsar
