# Default values for harness-delegate chart.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# These are the required values that are needed for harness-delegate
# chart deployment. You can download these account specific values by
# going to Harness > Setup > Installations page

# Account Id to which the delegate will be connecting
accountId: ""
# Account Secret
accountSecret: ""
# Short 6 character identifier of the account
accountIdShort: ""


# These are the prepopulated default values that are needed for
# harness-delegate chart deployment

# Delegate name
delegateName: harness-delegate
# If the RBAC scope is at cluster or namespace level
clusterWideRbacScope: true

# For connecting to Harness production SAAS environment, leave these
# values as it is. For on-prem installation, these will be overriden
# and you can download at Harness > Setup > Installations page
managerHostAndPort: https://app.harness.io
watcherStorageUrl: https://app.harness.io/storage/wingswatchers
watcherCheckLocation: watcherprod.txt
delegateStorageUrl: https://app.harness.io/storage/wingsdelegates
delegateCheckLocation: delegateprod.txt

# Delegate image to be deployed
image: harness/delegate:latest

# Delegate resource limits
resources:
  limits:
    cpu: "1"
    memory: "8Gi"
  requests:
    cpu: "500m"
    memory: "6Gi"

# If the harness delegate should go through proxy then set it to true
proxyManager: "true"
# If the proxy doesn't support web socket (wss) protocol then set it
# to true
pollForTasks: "false"

# Proxy settings if the delegate will be running behind proxy
proxyHost: ""
proxyPort: ""
proxyUser: ""
proxyPassword: ""

# Allowed values are http or https
proxyScheme: ""

# Enter a comma separated list of suffixes for which proxy is not
# required. Do not use leading wildcards (.company.com,specifichost)
# (optional):
noProxy: ""

# Id of the delegate profile that needs to run when the delegate is
# coming up
delegateProfile: ""

# Helm version to be installed in delegate
helmDesiredVersion: ""
