apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "storageos.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
