apiVersion: v1
description: A Fluentd Aggregator Helm chart Continuously Receive Events From The Log Forwarders.
icon: https://www.fluentd.org/assets/img/miscellany/fluentd-logo.png
name: fluentd-aggregator
version: 0.1.0
appVersion: v2.3.1
home: https://www.fluentd.org/
sources:
- https://www.fluentd.org/
maintainers:
- name: guangbochen
  email: support@rancher.com
