{{- if .Values.cluster.create }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.secretRefName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  apiUsername: {{ include "validate-username" . | b64enc | quote }}
  apiPassword: {{ include "validate-password" . | b64enc | quote }}
  # Add base64 encoded TLS cert and key below if ingress.tls is set to true.
  # tls.crt:
  # tls.key:
  # Add base64 encoded creds below for CSI credentials.
  csiProvisionUsername: {{ .Values.cluster.admin.username | b64enc | quote }}
  csiProvisionPassword: {{ .Values.cluster.admin.password | b64enc | quote }}
  csiControllerPublishUsername: {{ .Values.cluster.admin.username | b64enc | quote }}
  csiControllerPublishPassword: {{ .Values.cluster.admin.password | b64enc | quote }}
  csiNodePublishUsername: {{ .Values.cluster.admin.username | b64enc | quote }}
  csiNodePublishPassword: {{ .Values.cluster.admin.password | b64enc | quote }}
  csiControllerExpandUsername: {{ .Values.cluster.admin.username | b64enc | quote }}
  csiControllerExpandPassword: {{ .Values.cluster.admin.password | b64enc | quote }}

{{- end }}
