apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vault.name }}
  labels:
    app: {{ template "vault-operator.name" . }}
    chart: {{ template "vault-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  vault.hcl: |-
    ui = true
    disable_mlock = true
