apiVersion: v1
data:
  logger-config.yml: |-
    log-level: {{ .Values.agent.logLevel }}
    max-filesize-mb: {{ .Values.agent.maxLogFileSize }}
    max-backups: {{ .Values.agent.maxLogBackups }}
    write-to-stdout: {{ .Values.agent.writeToStdout }}
kind: ConfigMap
metadata:
  name: cluster-agent-log
  namespace: {{ .Release.Namespace }}
