apiVersion: v1
data:
  APPDYNAMICS_AGENT_ACCOUNT_NAME: {{ .Values.controller.accountName }}
  APPDYNAMICS_AGENT_PROXY_URL: {{ .Values.controller.proxyUrl | quote }}
  APPDYNAMICS_AGENT_PROXY_USER: {{ .Values.controller.proxyUser | quote }}
  APPDYNAMICS_CLUSTER_CONTAINER_REGISTRATION_INTERVAL: {{ .Values.agent.containerRegInterval | quote  }}
  APPDYNAMICS_CLUSTER_EVENT_UPLOAD_INTERVAL: {{ .Values.agent.eventUploadInterval | quote  }}
  APPDYNAMICS_CLUSTER_HTTP_CLIENT_TIMEOUT_INTERVAL: {{ .Values.agent.containerRegInterval | quote  }}
  APPDYNAMICS_CLUSTER_MONITORED_NAMESPACES: {{ .Values.agent.monitoredNamespaces }} 
  APPDYNAMICS_CLUSTER_NAME: {{ .Values.agent.appName }}
  APPDYNAMICS_CONTROLLER_HOST_NAME: {{ .Values.controller.dns | quote }}
  APPDYNAMICS_CONTROLLER_PORT: {{ .Values.controller.port | quote }}
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: {{ .Values.controller.ssl | quote }}
kind: ConfigMap
metadata:
  name: cluster-agent-config
  namespace: {{ .Release.Namespace }}
