apiVersion: v1
data:
  agent-monitoring.yml: "metric-collection-interval-seconds: {{ .Values.agent.metricsCollectionInterval }}\ncluster-metric-collection-interval-seconds:
    {{ .Values.agent.clusterMetricsCollectionInterval }}\nmetadata-collection-interval-seconds: {{ .Values.agent.metadataCollectionInterval }}\ncontainer-registration-batch-size:
    {{ .Values.agent.containerRegBatchSize }}\ncontainer-registration-max-parallel-requests: {{ .Values.agent.containerRegMaxParallelRequests }}\npod-registration-batch-size:
    {{ .Values.agent.podRegBatchSize }} \t\t\nmetric-upload-retry-count: {{ .Values.agent.metricUploadRetryCount }}\nmetric-upload-retry-interval-milliseconds:
    {{ .Values.agent.metricUploadRetryInterval }}\nmax-pods-to-register-count: {{ .Values.agent.maxPodsToRegister }}\ncontainer-filter:\n  {{ .Values.agent.containerFilter }}\n"
kind: ConfigMap
metadata:
  name: cluster-agent-mon
  namespace: {{ .Release.Namespace }}
