{{- if .Values.controller.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-secret
  labels:
    app: {{ template "cluster-agent.name" . }}
    chart: {{ template "cluster-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  controller-key: {{ .Values.controller.accessKey | b64enc | quote }}
{{- end }}
