apiVersion: v1
version: 1.12.0
name: openebs
appVersion: 1.12.0
description: Containerized Storage for Containers
icon: file://../openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - iSCSI
  - storage
sources:
  - https://github.com/openebs/openebs
maintainers:
  - name: kmova
    email: kiran.mova@openebs.io
  - name: prateekpandey14
    email: prateek.pandey@openebs.io
