{{ if .Values.defaultSecret }}
apiVersion: v1
data:
  sasl_password: YnJva2VydXNlcnNlY3JldA==
  sasl_username: YnJva2VydXNlcg==
kind: Secret
metadata:
  name: bluehub-exporter-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
