apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/name: kafka
  name: {{ template "bluehub.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.port | default "9308" | int }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port | default "9308" | int }}
  selector:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
