apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/name: kafka
  name: {{ template "bluehub.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: broker
    port: {{ .Values.nonsecurePort | default "9092" | int }}
    protocol: TCP
    targetPort: {{ .Values.nonsecurePort | default "9092" | int }}
  selector:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: {{ .Values.type | default "ClusterIP" | quote }}
