apiVersion: v1
name: portshift-operator
version: 0.1.0
appVersion: v0.1.3
description: |
  Portshift cloud-native security platform is an agentless security solution for containerized applications
keywords:
  - portshift
  - operator
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://www.portshift.io/
icon: file://../logo.png
maintainers:
  - name: idan
    email: idan@portshift.io
engine: gotpl
