artifactory:
  persistence:
    enabled: true

postgresql:
  image:
    tag: 9.6.15-debian-9-r91
  postgresqlPassword: "password"
  postgresqlExtendedConf:
    maxConnections: "102"
  persistence:
    enabled: true
