name: neuvector
apiVersion: v1
version: 1.5.1
appVersion: 3.2.1
description: NeuVector Full Lifecycle Container Security Platform delivers the only cloud-native security with uncompromising end-to-end protection from DevOps vulnerability protection to automated run-time security, and featuring a true Layer 7 container firewall.
home: https://neuvector.com
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
