{{- if not .Values.git.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flux.fullname" . }}-git-deploy
  {{- if .Values.ssh.secret.annotations }}
  annotations: {{ toYaml .Values.ssh.secret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
{{- end -}}
