{{ if .Values.defaultSecret }}
apiVersion: v1
data:
  default.json: ewogICJrYWZrYUNsaWVudCI6IHsKICAgICJyZXRyaWVzIjogMTAsCiAgICAiYnJva2VycyI6IFsiYmx1ZWh1Yi1rYWZrYS1oZWFkbGVzczo5MDkzIl0sCiAgICAiY2FjZXJ0IjogIi9vcHQva2Fma2EvY2VydHMvY2xpZW50LWNhLnBlbSIsCiAgICAidXNlcm5hbWUiOiAiYnJva2VydXNlciIsCiAgICAicGFzc3dvcmQiOiAiYnJva2VydXNlcnNlY3JldCIsCiAgICAibG9nTGV2ZWwiOiAiRVJST1IiLAogICAgImNvbm5lY3Rpb25UaW1lb3V0IjogMzAwMCwKICAgICJyZXF1ZXN0VGltZW91dCI6IDI1MDAwCiAgfSwKICAibXNnT3B0aW9ucyI6IHsKICAgICJ0b3BpYyI6ICJ0ZXN0dHAiLAogICAgInBhcnRpdGlvbnMiOiAzLAogICAgImNvbXByZXNzaW9uIjogdHJ1ZSwKICAgICJhY2tzIjogLTEsCiAgICAidGltZW91dCI6IDEwMDAwCiAgfSwKICAibGltaXRzIjogewogICAgInJhdGVMaW1pdENvdW50IjogMTAwLAogICAgInJhdGVMaW1pdEludGVydmFsIjogMTAwMAogIH0sCiAgInNjaGVtYXJlZyI6IHsKICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICJzY2hlbWEiOiAiZGVmYXVsdC5hdnNjIgogIH0sCiAgImVuY3J5cHRpb24iOiB7CiAgICAiZW5hYmxlZCI6IHRydWUsCiAgICAia2V5IjogInRoaXNpc215c2VjcmV0a2V5IgogIH0KfQ==
kind: Secret
metadata:
  name: {{ template "bluehub.fullname" . }}-producers-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
