{{ if .Values.defaultSecret }}
apiVersion: v1
data:
  default.avsc: ewogICJuYW1lIjogImRlZmF1bHQiLAogICJ0eXBlIjogInJlY29yZCIsCiAgIm5hbWVzcGFjZSI6ICJjb20uYXZyby5zY2hlbWFzIiwKICAiZmllbGRzIjogWwogICAgewogICAgICAibmFtZSI6ICJoZWFkZXIiLAogICAgICAidHlwZSI6IHsKICAgICAgICAibmFtZSI6ICJoZWFkZXIiLAogICAgICAgICJ0eXBlIjogInJlY29yZCIsCiAgICAgICAgImZpZWxkcyI6IFsKICAgICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAicmVmSUQiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICB9CiAgICAgICAgXQogICAgICB9CiAgICB9LAogICAgewogICAgICAibmFtZSI6ICJib2R5IiwKICAgICAgInR5cGUiOiB7CiAgICAgICAgIm5hbWUiOiAiYm9keSIsCiAgICAgICAgInR5cGUiOiAicmVjb3JkIiwKICAgICAgICAiZmllbGRzIjogWwogICAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJtc2ciLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICB9CiAgICAgICAgXQogICAgICB9CiAgICB9CiAgXQp9
kind: Secret
metadata:
  name: {{ template "bluehub.fullname" . }}-schemas-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
