apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "kproducer.name" . }}
    release: {{ .Release.Name }}
  name: {{ template "bluehub.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ template "bluehub.fullname" . }}
    port: {{ .Values.port | default "3443" | int }}
    protocol: TCP
    targetPort: {{ .Values.port | default "3443" | int }}
  selector:
    app: {{ template "kproducer.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.type | default "ClusterIP" | quote }}
