{{- if .Values.chainerOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chainer-operator
    ksonnet.io/component: chainer-operator
  name: chainer-operator
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainer-operator
  template:
    metadata:
      labels:
        app: chainer-operator
    spec:
      containers:
      - args:
        - -v
        - "2"
        - -stderrthreshold
        - INFO
        image: "{{ .Values.chainerOperator.image.repository }}:{{ .Values.chainerOperator.image.tag }}"
        imagePullPolicy: Always
        name: chainer-operator
      serviceAccountName: chainer-operator
{{- end }}
