{{- if .Values.chainerOperator.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ksonnet.io/component: chainer-operator
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": before-hook-creation
  name: chainerjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    categories:
    - all
    kind: ChainerJob
    plural: chainerjobs
    shortNames:
    - chj
    - chjs
    - chjob
    - chjobs
    singular: chainerjob
  scope: Namespaced
  version: v1alpha1
{{- end }}
