apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: core
    ksonnet.io/component: katib
  name: vizier-core
  namespace: kubeflow
spec:
  ports:
  - name: api
    {{- if .Values.katib.vizier.service.nodePort }}
    nodePort: {{ .Values.katib.vizier.service.nodePort }}
    {{- end }}
    port: 6789
    protocol: TCP
  selector:
    app: vizier
    component: core
  type: {{ .Values.katib.vizier.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: db
    ksonnet.io/component: katib
  name: vizier-db
  namespace: kubeflow
spec:
  ports:
  - name: dbapi
    port: 3306
    protocol: TCP
  selector:
    app: vizier
    component: db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: suggestion-bayesianoptimization
    ksonnet.io/component: katib
  name: vizier-suggestion-bayesianoptimization
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: vizier
    component: suggestion-bayesianoptimization
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: suggestion-grid
    ksonnet.io/component: katib
  name: vizier-suggestion-grid
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: vizier
    component: suggestion-grid
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: suggestion-hyperband
    ksonnet.io/component: katib
  name: vizier-suggestion-hyperband
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: vizier
    component: suggestion-hyperband
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vizier
    component: suggestion-random
    ksonnet.io/component: katib
  name: vizier-suggestion-random
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6789
    protocol: TCP
  selector:
    app: vizier
    component: suggestion-random
  type: ClusterIP
