apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
    component: backend
    ksonnet.io/component: katib
  name: modeldb-backend
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 6543
    protocol: TCP
  selector:
    app: modeldb
    component: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
    component: db
    ksonnet.io/component: katib
  name: modeldb-db
  namespace: kubeflow
spec:
  ports:
  - name: dbapi
    port: 27017
    protocol: TCP
  selector:
    app: modeldb
    component: db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: modeldb-mapping
      prefix: /katib/
      rewrite: /katib/
      method: GET
      service: modeldb-frontend.kubeflow:3000
  labels:
    app: modeldb
    component: frontend
    ksonnet.io/component: katib
  name: modeldb-frontend
  namespace: kubeflow
spec:
  ports:
  - name: api
    port: 3000
    protocol: TCP
  selector:
    app: modeldb
    component: frontend
  type: ClusterIP
