apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ksonnet.io/component: katib
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": before-hook-creation
  name: studyjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: StudyJob
    plural: studyjobs
    singular: studyjob
  version: v1alpha1
