{{- if .Values.tfJobOperator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: tf-job-operator
  name: tf-job-operator-config
  namespace: kubeflow
data:
  controller_config_file.yaml: |-
    {
        "grpcServerFilePath": "/opt/mlkube/grpc_tensorflow_server/grpc_tensorflow_server.py"
    }
{{- end }}
