# Default values for citrix-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# image contains information needed to fetch CIC image
image: quay.io/citrix/citrix-k8s-ingress-controller:1.8.19
pullPolicy: Always
# openshift is set to true if charts are being deployed in OpenShift environment.
openshift: false
# loginFileName is secret file for NetScaler login
loginFileName:
# nsIP is NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
nsIP: x.x.x.x
nsVIP:
# license accept should be 'yes' to run Citrix Ingress Controller
license:
   accept: no
# nsPort is port for NetScaler NITRO
nsPort: 443
# nsProtocol is protocol for NetScaler NITRO
nsProtocol: HTTPS
# logLevel is to set level of CIC Logs
logLevel: DEBUG
# nsNamespace is the prefix for the resources on the Citrix ADC
nsNamespace:
# kubernetesURL is for registering events to kubeapi server
kubernetesURL:
# ingressClass is the name of the Ingress Class
ingressClass:
# Default SSL certificate
defaultSSLCert:
# Set this argument if you want to use the IPAM controller
ipam: False
# Elasticsearch or Kafka or Zipkin endpoint for Citrix observability exporter
logProxy:
# nodeWatch is used for automatic route configuration on NetScaler towards the pod network
nodeWatch: false
# Set to ON to enables HTTP2 for Citrix ADC service group configurations
http2ServerSide: "OFF"
# exporter conatins information of prometheus-exporter
exporter:
   required: false
   image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.3
   pullPolicy: Always
   ports:
      containerPort: 8888
crds:
# If false, CustomResourceDefinitions  will not be installed.
   install: true
# if set to true, then CustomResourceDefinitions will not be deleted during helm delete. This way, CustomResourceObjects will not be deleted from the database.
   retainOnDelete: false
