apiVersion: v1
appVersion: 5.7.2
description: Enable Kubernetes as a backend for OpenFaaS (Functions as a Service)
name: openfaas
version: 5.7.2
sources:
- https://github.com/openfaas/faas
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: file://../logo.png
keywords:
- functions
- service
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: lucasroesler
  email: roesler.lucas@gmail.com
- name: stefanprodan
  email: stefan.prodan@gmail.com
