apiVersion: v1
appVersion: 6.15.0
description: JFrog Container Registry
home: https://www.jfrog.com/artifactory/
icon: file://../jfrog_med.png
keywords:
- artifactory
- jfrog
- container
- registry
- devops
- jfrog-container-registry
maintainers:
- email: amithk@jfrog.com
  name: amithins
- email: daniele@jfrog.com
  name: danielezer
- email: eldada@jfrog.com
  name: eldada
- email: rimasm@jfrog.com
  name: rimusz
- email: vinaya@jfrog.com
  name: vinaya
name: artifactory-jcr
sources:
- https://github.com/jfrog/charts
version: 0.1.0
