# Default values for artifactory-jcr.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# This chart is based on the main artifactory chart with some customizations.
# See all supported configuration keys in https://github.com/jfrog/charts/tree/master/stable/artifactory

## All values are under the 'artifactory' sub chart.
artifactory:

  ## Artifactory
  ## See full list of supported Artifactory options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  artifactory:
    image:
      repository: docker.bintray.io/jfrog/artifactory-jcr

      ## Default version is from the artifactory sub-chart in the requirements.yaml
      # version:

  installer:
    platform: jcr-helm

  ## Nginx
  ## See full list of supported Nginx options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  nginx:
    enabled: true
    tlsSecretName: ""
    service:
      type: LoadBalancer

  ## Ingress
  ## See full list of supported Ingress options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  ingress:
    enabled: false
    tls:

  ## PostgreSQL
  ## Configuration values for the PostgreSQL dependency sub-chart
  ## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
  postgresql:
    enabled: true

  ## This key is required for upgrades to protect old PostgreSQL chart's breaking changes.
  databaseUpgradeReady: yes

  ## If NOT using the PostgreSQL in this chart (artifactory.postgresql.enabled=false),
  ## specify custom database details here or leave empty and Artifactory will use embedded derby.
  ## See full list of database options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  database:


## Enable the PostgreSQL sub chart
postgresql:
  enabled: true
