{{ if .Values.defaultSecret }}
apiVersion: v1
data:
  clustermgr_password: YWRtaW4=
  clustermgr_username: YWRtaW4=
kind: Secret
metadata:
  name: {{ template "bluehub.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
