apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "clustermgr.name" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  name: {{ template "bluehub.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ template "bluehub.fullname" . }}
    port: {{ .Values.port | default "9000" | int }}
    protocol: TCP
    targetPort: {{ .Values.port | default "9000" | int }}
  selector:
    app: {{ template "clustermgr.name" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  sessionAffinity: None
  type: {{ .Values.type | default "ClusterIP" | quote }}
