apiVersion: v1
name: lightstep
version: 0.1.0
appVersion: latest
description: Lightsep satellite to receive telemetry data.
home: https://lightstep.com/
icon: file://../lightstep-logo.png
engine: gotpl
maintainers:
- name: ajohnsonls
  email: ajohnsonls@lightstep.com
