{{- if .Values.controller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-controller
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 18300
      protocol: "TCP"
      name: "cluster-tcp-18300"
    - port: 18301
      protocol: "TCP"
      name: "cluster-tcp-18301"
    - port: 18301
      protocol: "UDP"
      name: "cluster-udp-18301"
  clusterIP: None
  selector:
    app: neuvector-controller-pod
{{- end }}