{{- if .Values.manager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-webui
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if or .Values.openshift .Values.manager.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: {{ .Values.manager.svc.type }}
{{- end }}
  ports:
    - port: 8443
      name: manager
      protocol: TCP
  selector:
    app: neuvector-manager-pod
{{- end }}