apiVersion: v1
description: Message broker supports message patterns of Active Queue, Command-Query and Pub-Sub events.
appVersion: "1.0"
name: kubemq
keywords:
- message
- event
- queue
home: https://kubemq.io/
version: 0.1.0
sources:
- https://github.com/kubemq-io/docs
maintainers:
- name: ido-sheffer
  email: ido.sheffer@kubemq.io
icon: file://./kubemqlogo.png
