apiVersion: v1
appVersion: "1.8.19"
description: A Helm chart for Citrix API Gateway.
name: citrix-api-gateway
version: 1.8.19
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
- name: subashd
  email: subash.dangol@citrix.com
