{{- if .Values.lightstep.satelliteKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: lightstep-satellite
  labels:
    app: "{{ template "lightstep.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
stringData:
  satelliteKey: {{ .Values.lightstep.satelliteKey  }}
{{- end }}