# Default values for kubeflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
applicationController:
  project: test

argo:
  executorImage: argoproj/argoexec:v2.3.0
  artifactRepositoryBucket: mlpipeline
  artifactRepositoryKeyPrefix: artifacts
  artifactRepositoryEndpoint: minio-service.kubeflow:9000
  artifactRepositoryInsecure: true
  artifactRepositoryAccessKeySecretName: mlpipeline-minio-artifact
  artifactRepositoryAccessKeySecretKey: accesskey
  artifactRepositorySecretKeySecretName: mlpipeline-minio-artifact
  artifactRepositorySecretKeySecretKey: secretkey

centraldashboard:
  useridHeader: ""
  useridPrefix: ""

clusterDomain: cluster.local

istio:
  clusterRbacConfig: "OFF"

jupyterWebApp:
  ui: default
  rokSecretName: secret-rok-{username}
  policy: Always
  prefix: jupyter
  useridHeader: ""
  useridPrefix: ""

katib:
  db:
    password: test
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""

metadata:
  db:
    password: test
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""

minio:
  accessKey: minio
  secretKey: minio123
  persistence:
    enabled: true
  accessMode: ReadWriteOnce
  pvcName: minio-pvc
  size: 20Gi
  storageClass: ""

mysql:
  persistence:
    enabled: true
  accessMode: ReadWriteOnce
  pvcName: mysql-pvc
  size: 20Gi
  storageClass: ""

notebookController:
  podLabels: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
  useIstio: true

profiles:
  admin: johnDoe@acme.com
  useridHeader: ""
  useridPrefix: ""

spartakus:
  usageId: test
