{{- if .Values.priority }}
{{- if .Values.priority.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-priority
value: {{ .Values.priority.value | default "1000000" }}
globalDefault: false
description: "Priority class for scheduling the cost-analyzer pod"
{{- end }}
{{- end }}